/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "system_stm32f4xx.h"
#include "timer.h"
#include "eventman.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/*------------------Private datatyped ------------------------*/

/*! @brief Events APIs*/
typedef enum {
	EVENT_EMPTY, EVENT_APP_INIT, EVENT_APP_FLUSHMEM_READY,
} event_api_t, *event_api_p;

typedef enum {
	STATE_APP_STARTUP, STATE_APP_IDLE, STATE_APP_RESET
} state_app_t;

/*------------------Private variable-------------------------*/
static state_app_t eCurrentState;
static ucg_t ucg;
static uint8_t led_state_b1;
static uint8_t led_state_b2;
static uint8_t led_state_b4;
static uint8_t led_state_b5;
static uint8_t led_level = 0;
static uint8_t state = 0;
static uint8_t ignoreSensorTime;
static SSwTimer idTimerSensorScan = NO_TIMER;
static SSwTimer idTimerLedLevel = NO_TIMER;

/*------------------Private function prototypes-------------------------*/

/*
 * @func	Task_multiSesorScan()
 * @brief	Get temperature,humidity and light from sensor then display on LCD
 * @param	None
 * retval	None
 * */
static void Task_multiSensorScan() {

	static uint8_t temperature, humidity;
	static uint16_t light;

	static char strTemp[20] = "";
	static char strHumi[20] = "";
	static char strLight[20] = "";

	memset(strTemp, 0, sizeof(strTemp));
	memset(strHumi, 0, sizeof(strHumi));
	memset(strLight, 0, sizeof(strLight));

	//Skip 5s after press B5 5 times
	if (ignoreSensorTime > 0) {
		--ignoreSensorTime;

	} else {
		temperature = (uint8_t) (TemHumSensor_GetTemp() / 100);
		humidity = (uint8_t) (TemHumSensor_GetHumi() / 100);
		light = LightSensor_MeasureUseDMAMode();

		if (state == 0) {
			ucg_ClearScreen(&ucg);
			state = 1;
		}
		ucg_SetFont(&ucg, ucg_font_ncenR10_hf);

		sprintf(strTemp, "Temp =  %d%d oC", (temperature / 10),
				(temperature % 10));
		ucg_DrawString(&ucg, 8, 50, 0, strTemp);

		sprintf(strHumi, "Humi =  %d%d %%", (humidity / 10), (humidity % 10));
		ucg_DrawString(&ucg, 8, 75, 0, strHumi);

		sprintf(strLight, "Light = %d%d%d%d lux", (light / 1000),
				(light / 100) % 10, (light / 10) % 10, (light % 10));
		ucg_DrawString(&ucg, 8, 100, 0, strLight);

	}

}

/**
 * @func 	SetStateApp
 * @brief 	Set state of application
 * @param 	state: State of application
 * @retval	None
 */
static void SetStateApp(state_app_t state) {
	/* Set state of application */
	eCurrentState = state;
}

/**
 * @func 	GetStateApp
 * @brief 	Get state of application
 * @param 	None
 * @retval	State of application
 */
static state_app_t GetStateApp(void) {
	/* Return state of application */
	return eCurrentState;
}

/**
 * @func    LoadConfiguaration
 * @brief 	Display string on LCD
 * @param 	None
 * @retval	None
 */
static void LoadConfiguration(void) {
	ucg_DrawString(&ucg, 45, 30, 0, "IOT");
	ucg_DrawString(&ucg, 6, 50, 0, "Programming by");
	ucg_DrawString(&ucg, 4, 75, 0, "Lumi Smarthome");

	LedControl_SetAllColor(LED_COLOR_WHITE, 0);
}

/*
 * @func 	Increase_LedLevel
 * @brief	Increase led level
 * @param	None
 * @retval	None
 * */
static void Increase_LedLevel(void *arg) {
	if (led_level >= 0 && led_level < 100) {
		led_level += 1;
		LedControl_SetAllColor(LED_COLOR_GREEN, led_level);
	}
}

/*
 * @func	Decrease_LedLevel
 * @brief	Decrease_LedLevel
 * @param	None
 * @retval	None
 * */
static void Decrease_LedLevel(void *arg) {
	if (led_level > 0 && led_level <= 100) {
		led_level -= 1;
		LedControl_SetAllColor(LED_COLOR_GREEN, led_level);
	}
}

/*
 * @func	DeviceStateMachine
 * @brief	State machine of the device
 * @param	uint8_t event
 * @retval  None
 */
void DeviceStateMachine(uint8_t event) {
	switch (event) {
	case EVENT_OF_BUTTON_3_PRESS_5_TIMES:
	case EVENT_OF_BUTTON_0_PRESS_5_TIMES: {
		// Blink led green 5 times
		LedControl_BlinkStart(LED_ALL_ID, BLINK_GREEN, 10, 500,
				LED_COLOR_BLACK);

		// Display information of device
		ucg_ClearScreen(&ucg);
		ucg_SetFont(&ucg, ucg_font_ncenR08_tr);

		ucg_DrawString(&ucg, 0, 20, 0, "Device: Board STM32");
		ucg_DrawString(&ucg, 0, 35, 0, "Nucleo.");
		ucg_DrawString(&ucg, 0, 50, 0, "Code: STM32F401RE");
		ucg_DrawString(&ucg, 0, 65, 0, "NUCLEO.");
		ucg_DrawString(&ucg, 0, 80, 0, "Manufacturer:");
		ucg_DrawString(&ucg, 0, 95, 0, "STMicroelectonics.");
		ucg_DrawString(&ucg, 0, 110, 0, "Kit expansion:");
		ucg_DrawString(&ucg, 0, 125, 0, "Lumi Smarthome");
		ucg_DrawString(&ucg, 0, 140, 0, "Project:");
		ucg_DrawString(&ucg, 0, 155, 0, "Simulator touch switch.");

		state = 0;

		//Start timer scan sensor after time is 1s
		if (idTimerSensorScan != NO_TIMER) {
			TimerStop(idTimerSensorScan);
		}

		idTimerSensorScan = TimerStart("Task_multiSensor", 1000,
		TIMER_REPEAT_FOREVER, Task_multiSensorScan, NULL);

	}
		break;

	case EVENT_OF_BUTTON_1_PRESS_LOGIC: {
		if (led_state_b1 == 0) {
			LedControl_SetAllColor(LED_COLOR_RED, 50);
			BuzzerControl_SetMelody(pbeep);
			led_state_b1 = 1;
		} else {
			LedControl_SetAllColor(LED_COLOR_RED, 0);
			BuzzerControl_SetMelody(pbeep);
			led_state_b1 = 0;
		}

	}
		break;

	case EVENT_OF_BUTTON_2_PRESS_LOGIC: {
		if (led_state_b2 == 0) {
			LedControl_SetAllColor(LED_COLOR_GREEN, 50);
			BuzzerControl_SetMelody(pbeep);
			led_state_b2 = 1;
		} else {
			LedControl_SetAllColor(LED_COLOR_GREEN, 0);
			BuzzerControl_SetMelody(pbeep);
			led_state_b2 = 0;
		}
	}
		break;

	case EVENT_OF_BUTTON_4_PRESS_LOGIC: {
		if (led_state_b4 == 0) {
			LedControl_SetAllColor(LED_COLOR_YELLOW, 50);
			BuzzerControl_SetMelody(pbeep);
			led_state_b4 = 1;
		} else {
			LedControl_SetAllColor(LED_COLOR_YELLOW, 0);
			BuzzerControl_SetMelody(pbeep);
			led_state_b4 = 0;
		}
	}
		break;

	case EVENT_OF_BUTTON_5_PRESS_LOGIC: {
		if (led_state_b5 == 0) {
			LedControl_SetAllColor(LED_COLOR_BLUE, 60);
			BuzzerControl_SetMelody(pbeep);
			led_state_b5 = 1;
		} else {
			LedControl_SetAllColor(LED_COLOR_BLUE, 0);
			BuzzerControl_SetMelody(pbeep);
			led_state_b5 = 0;
		}
	}
		break;

	case EVENT_OF_BUTTON_1_HOLD_1S: {
		if (idTimerLedLevel != NO_TIMER) {
			TimerStop(idTimerLedLevel);
		}
		idTimerLedLevel = TimerStart("Increase_LedLevel", 20, 100,
				Increase_LedLevel, NULL);

	}
		break;

	case EVENT_OF_BUTTON_5_HOLD_1S: {
		if (idTimerLedLevel != NO_TIMER) {
			TimerStop(idTimerLedLevel);
		}
		idTimerLedLevel = TimerStart("Decrease_LedLevel", 20, 100,
				Decrease_LedLevel, NULL);
	}
		break;

	case EVENT_OF_BUTTON_1_RELEASED_1S:
	case EVENT_OF_BUTTON_5_RELEASED_1S:
		TimerStop(idTimerLedLevel);
		break;

	default:
		break;

	}
}

/**
 * @func 	AppStateManager
 * @brief 	Manager state application
 * @param 	None
 * @retval	None
 */
static void AppStateManager(uint8_t event) {
	switch (GetStateApp()) {
	case STATE_APP_STARTUP:
		if (event == EVENT_APP_INIT) {
			// Load configuration
			LoadConfiguration();
			SetStateApp(STATE_APP_IDLE);
		}
		break;

	case STATE_APP_IDLE:
		DeviceStateMachine(event);
		break;

	case STATE_APP_RESET:
		break;

	default:
		break;
	}
}

/**
 * @func 	AppInitCommon
 * @brief 	Manager state application
 * @param 	None
 * @retval	None
 */
static void AppInitCommon() {
	// Initializes system clock 84 MHz
	SystemCoreClockUpdate();

	//Initializes system tick
	TimerInit();

	// Initializes scheduler event
	EventSchedulerInit(AppStateManager);

	// Initializes buttons
	EventButton_Init();

	// Initializes buzzer
	BuzzerControl_Init();

	// Initializes led
	LedControl_Init();

	// Initializes light sensor
	LightSensor_Init(ADC_READ_MODE_DMA);

	// Initializes temperature and humidity sensor
	TemHumSensor_Init();

	// Initializes LCD
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);

	ucg_SetFont(&ucg, ucg_font_ncenR10_hf);
	ucg_SetColor(&ucg, 0, 255, 255, 255);
	ucg_SetColor(&ucg, 1, 0, 0, 0);
	ucg_SetRotate180(&ucg);

}

int main(void) {
	AppInitCommon();
	SetStateApp(STATE_APP_STARTUP);
	EventSchedulerAdd(EVENT_APP_INIT);
	/* Loop forever */
	while (1) {
		processTimerScheduler();
		processEventScheduler();

	}
}

